{{- if .Values.envConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-exporter-helm.fullname" . }}-configmap
  labels:
    {{- include "query-exporter-helm.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envConfig | nindent 2 }}
{{ end }}
{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-exporter-helm.fullname" . }}-exporter-config
  labels:
    {{- include "query-exporter-helm.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.config | indent 2 }}
{{ end }}
